name: DevInfra

on:
  issues:
    types: [opened, reopened]

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  issue_labels:
    if: github.event_name == 'issues'
    runs-on: ${{ fromJSON(vars.CI_RUNNER_LABELS) }}
    steps:
      - uses: angular/dev-infra/github-actions/labeling/issue@649c3afeaa46674507b9625537e49de54a695e2b
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
          google-generative-ai-key: ${{ secrets.GOOGLE_GENERATIVE_AI_KEY }}
